Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    
    config.vm.define "jilerouxS" do |server|
      server.vm.hostname = "jilerouxS"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
  
      server.vm.synced_folder ".", "/vagrant"
  
      server.vm.provision "shell", inline: <<-SHELL
        curl -sfL https://get.k3s.io | sh -
        sleep 10
        sudo kubectl apply -f /vagrant/confs/
        
        echo "192.168.56.110 app1.com" | sudo tee -a /etc/hosts
        echo "192.168.56.110 app2.com" | sudo tee -a /etc/hosts
        echo "192.168.56.110 app3.com" | sudo tee -a /etc/hosts
      SHELL
    end
  end