
cpus           = ENV['CPUS'] || 1
memory         = ENV['MEMORY'] || 1024

BOX            = ENV['VERSION'] || "debian/bullseye64"
SERVER_NAME    = "sleonS"
WORKER_NAME    = "sleonSW"
SERVER_IP      = "192.168.56.110"
WORKER_IP      = "192.168.56.111"
Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.provider "virtualbox" do |vb|
    vb.memory = memory 
    vb.cpus = cpus
  end

  # # Server vm
  config.vm.define SERVER_NAME do |sleonS|
    sleonS.vm.hostname = SERVER_NAME
    sleonS.vm.synced_folder "config/", "/vagrant" 
    sleonS.vm.network "private_network", ip: SERVER_IP 
    sleonS.vm.provision "shell", path: "config/server.sh", args: [SERVER_IP] 
  end

  # # Worker vm
  config.vm.define WORKER_NAME do |sleonSW|
      sleonSW.vm.hostname = WORKER_NAME
      sleonSW.vm.synced_folder "config/", "/vagrant"
      sleonSW.vm.network "private_network", ip: WORKER_IP
      sleonSW.vm.provision "shell", path: "config/worker.sh", args: [SERVER_IP, WORKER_IP]
  end

end