Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  
    config.vm.define "jilerouxS" do |server|
      server.vm.hostname = "jilerouxS"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provision "shell", inline: <<-SHELL
        curl -sfL https://get.k3s.io | sh -
        cat /var/lib/rancher/k3s/server/node-token > /vagrant/k3s_token
        sudo chmod 644 /etc/rancher/k3s/k3s.yaml
      SHELL
    end
  
    config.vm.define "sleonSW" do |worker|
      worker.vm.hostname = "sleonSW"
      worker.vm.network "private_network", ip: "192.168.56.111"
  
      worker.vm.provision "shell", inline: <<-SHELL
        TOKEN=$(cat /vagrant/k3s_token)
        curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$TOKEN sh -
      SHELL
    end
  end